<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CFCNF77" name="Home Loan" tests="4" failures="1" timestamp="8 Oct 2019 13:39:30 GMT" time="0.083" errors="0">
  <testcase name="loginAPIHomeLoan" time="0.011" classname="test.day4">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.day4.loginAPIHomeLoan(day4.java:39)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginAPIHomeLoan -->
  <testcase name="webloginHomeLoan" time="0.016" classname="test.day4"/>
  <testcase name="verifyParameterization" time="0.003" classname="test.day4"/>
  <testcase name="MobileloginHomeLoan" time="0.001" classname="test.day4">
    <skipped/>
  </testcase> <!-- MobileloginHomeLoan -->
</testsuite> <!-- Home Loan -->
